# Generated by Django 4.0.3 on 2022-04-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HWblogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='programming', max_length=50),
        ),
    ]
