# Generated by Django 4.0.3 on 2022-04-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HWblogApp', '0002_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.CharField(default='2021-01-02 22:41:10.181347', max_length=50),
        ),
    ]
