# Generated by Django 4.0.3 on 2022-04-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HWblogApp', '0003_article_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateTimeField(default='2021-01-02 22:41:10.181347'),
        ),
    ]
