# Generated by Django 4.0.3 on 2022-04-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0007_alter_todo_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='remainday',
            field=models.IntegerField(null=True),
        ),
    ]
